---
- name: Gathering facts of all nodes
  hosts: all
  tasks:
  - setup:

- name: Install server(s)
  hosts: ombt-server
  roles:
    - ombt
  vars:
    enos_action: deploy
    agent_type: rpc-server

- name: Install client(s)
  hosts: ombt-client
  roles:
    - ombt
  vars:
    enos_action: deploy
    agent_type: rpc-client

- name: Install controller(s)
  hosts: ombt-control
  roles:
    - ombt
  vars:
    enos_action: deploy
    agent_type: controller

- name: Backup controller(s)
  hosts: ombt-control
  roles:
    - ombt
  vars:
    enos_action: backup
    agent_type: controller


- name: Backup client(s)
  hosts: ombt-client
  roles:
    - ombt
  vars:
    enos_action: backup
    agent_type: rpc-client

- name: Backup server(s)
  hosts: ombt-server
  roles:
    - ombt
  vars:
    enos_action: backup
    agent_type: rpc-server

- name: Backup influxdb
  hosts: influxdb
  roles:
    - influxdb
  vars:
   - enos_action: backup

- name: Backup buses
  hosts: bus
  roles:
    - { role: rabbitmq,
        when: broker == "rabbitmq" }
    - { role: qdr,
        when: broker == "qdr" }
  vars:
   - enos_action: backup

- name: Backup buses
  hosts: control-bus
  roles:
    - rabbitmq-control
  vars:
   - enos_action: backup
